import * as fs from 'fs'
import * as path from 'path'
import { createHash } from 'crypto'
import { resolveClaudeConfigDir, statusDir } from './claude-paths'

/**
 * Claude only delivers the subscription rate-limit usage (the 5h / 7d windows)
 * through its status-line hook — it is not written to any transcript or cache.
 * To read it, we install a small wrapper as the config dir's `statusLine.command`
 * that captures the status JSON Claude pipes in, writes it to a file keyed by
 * session id (which {@link usage.service} watches), and then runs the user's
 * previous status-line command unchanged so their visible status line is intact.
 *
 * POSIX only: on Windows we skip installation (transcript-based cost/tokens still
 * work; only the rate-limit overlay is unavailable).
 */

const isWindows = process.platform === 'win32'

/** Bump when the wrapper template changes so existing installs get regenerated. */
const WRAPPER_VERSION = 1

/** Quote a string for safe single-quoted embedding in a POSIX shell script. */
function shellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

function wrapperPath(configDir: string): string {
  const slug = createHash('sha1').update(configDir).digest('hex').slice(0, 12)
  return path.join(statusDir(), `statusline-${slug}.sh`)
}

function wrapperScript(prevCommand: string): string {
  const dir = statusDir()
  return `#!/bin/sh
# Generated by Superior (v${WRAPPER_VERSION}) to capture Claude usage for its
# terminal topbar. Safe to delete — Superior recreates it. It stores the status
# JSON, then runs your previous status line unchanged.
STATUS_DIR=${shellSingleQuote(dir)}
PREV=${shellSingleQuote(prevCommand)}
payload=$(cat)
sid=$(printf '%s' "$payload" | sed -n 's/.*"session_id"[[:space:]]*:[[:space:]]*"\\([0-9A-Za-z-]*\\)".*/\\1/p' | head -n1)
if [ -n "$sid" ]; then
  mkdir -p "$STATUS_DIR" 2>/dev/null
  printf '%s' "$payload" > "$STATUS_DIR/$sid.json.tmp" 2>/dev/null && mv "$STATUS_DIR/$sid.json.tmp" "$STATUS_DIR/$sid.json" 2>/dev/null
fi
if [ -n "$PREV" ]; then
  printf '%s' "$payload" | eval "$PREV"
fi
`
}

interface ClaudeSettings {
  statusLine?: { type?: string; command?: string; padding?: number }
  [key: string]: unknown
}

function readSettings(file: string): ClaudeSettings | null {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf-8')) as ClaudeSettings
  } catch (err) {
    // Missing file is fine (we create one); a malformed file is not — never
    // clobber settings we can't parse.
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return {}
    return null
  }
}

/**
 * Ensure the config dir backing `command` routes its status line through the
 * Superior wrapper. Idempotent. A no-op for non-Claude commands and on Windows.
 * Returns true when the wrapper is in place.
 */
export function ensureClaudeStatusline(command: string): boolean {
  if (isWindows) return false
  const configDir = resolveClaudeConfigDir(command)
  if (!configDir) return false

  const wrapper = wrapperPath(configDir)
  const settingsFile = path.join(configDir, 'settings.json')

  try {
    fs.mkdirSync(statusDir(), { recursive: true })

    const settings = readSettings(settingsFile)
    if (!settings) return false // unparseable — leave it untouched

    const current = settings.statusLine?.command
    const alreadyOurs = current === wrapper

    // Generate the wrapper on first install, when it's gone missing, or when the
    // template version bumps. When taking over, capture the user's existing command
    // so we can chain it; when already ours, keep the command the existing wrapper
    // baked in (the live command is the wrapper itself, so re-reading it is wrong).
    const stale = alreadyOurs && !wrapperIsCurrent(wrapper)
    if (!alreadyOurs || stale) {
      const prev = alreadyOurs ? readBakedPrev(wrapper) : current ?? ''
      fs.writeFileSync(wrapper, wrapperScript(prev), { mode: 0o755 })
    }

    if (!alreadyOurs) {
      settings.statusLine = {
        type: 'command',
        command: wrapper,
        ...(settings.statusLine?.padding !== undefined
          ? { padding: settings.statusLine.padding }
          : {})
      }
      // Atomic replace so a Claude reading settings.json never sees a half-written file.
      const tmp = `${settingsFile}.superior.tmp`
      fs.writeFileSync(tmp, `${JSON.stringify(settings, null, 2)}\n`, 'utf-8')
      fs.renameSync(tmp, settingsFile)
    }
    return true
  } catch {
    return false // best-effort — usage simply falls back to transcript data
  }
}

/** True when an existing wrapper was generated by the current template version. */
function wrapperIsCurrent(wrapper: string): boolean {
  try {
    return fs.readFileSync(wrapper, 'utf-8').includes(`(v${WRAPPER_VERSION})`)
  } catch {
    return false // missing/unreadable — treat as stale so it gets regenerated
  }
}

/** Recover the previous command baked into an existing wrapper (PREV='...'). */
function readBakedPrev(wrapper: string): string {
  try {
    const text = fs.readFileSync(wrapper, 'utf-8')
    const m = text.match(/^PREV='((?:[^'\\]|\\.|'\\'')*)'/m)
    if (!m) return ''
    return m[1].replace(/'\\''/g, `'`)
  } catch {
    return ''
  }
}
