import * as fs from 'fs'
import * as path from 'path'
import { createHash } from 'crypto'
import { resolveClaudeConfigDir, statusDir } from './claude-paths'

/**
 * Claude only delivers the subscription rate-limit usage (the 5h / 7d windows)
 * through its status-line hook — it is not written to any transcript or cache.
 * To read it, we install a small wrapper as the config dir's `statusLine.command`
 * that captures the status JSON Claude pipes in, writes it to a file keyed by
 * session id (which {@link usage.service} watches), and then runs the user's
 * previous status-line command unchanged so their visible status line is intact.
 *
 * POSIX only: on Windows we skip installation (transcript-based cost/tokens still
 * work; only the rate-limit overlay is unavailable).
 */

const isWindows = process.platform === 'win32'

/** Bump when the wrapper template changes so existing installs get regenerated. */
const WRAPPER_VERSION = 1

/** Quote a string for safe single-quoted embedding in a POSIX shell script. */
function shellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

function slugFor(configDir: string): string {
  return createHash('sha1').update(configDir).digest('hex').slice(0, 12)
}

function wrapperPath(configDir: string): string {
  return path.join(statusDir(), `statusline-${slugFor(configDir)}.sh`)
}

/**
 * Where we persist a config dir's genuine original statusLine before taking it
 * over. This is the source of truth for restoring it when tracking is disabled —
 * independent of the wrapper file, so a deleted wrapper can't strand the user
 * with our command and no way back.
 */
function backupPath(configDir: string): string {
  return path.join(statusDir(), `statusline-backup-${slugFor(configDir)}.json`)
}

interface StatuslineBackup {
  configDir: string
  /** The original statusLine object, or null when the user had none. */
  statusLine: ClaudeSettings['statusLine'] | null
}

/** Persist a config dir's original statusLine so disabling can restore it. */
function writeBackup(configDir: string, original: ClaudeSettings['statusLine'] | undefined): void {
  try {
    fs.mkdirSync(statusDir(), { recursive: true })
    const data: StatuslineBackup = { configDir, statusLine: original ?? null }
    fs.writeFileSync(backupPath(configDir), `${JSON.stringify(data, null, 2)}\n`, 'utf-8')
  } catch {
    // Best-effort: without a backup we fall back to the wrapper's baked PREV.
  }
}

/** Read a persisted backup, or null if it's missing/unreadable. */
function readBackup(file: string): StatuslineBackup | null {
  try {
    const data = JSON.parse(fs.readFileSync(file, 'utf-8')) as Partial<StatuslineBackup>
    if (typeof data.configDir !== 'string') return null
    return { configDir: data.configDir, statusLine: data.statusLine ?? null }
  } catch {
    return null
  }
}

function wrapperScript(prevCommand: string): string {
  const dir = statusDir()
  return `#!/bin/sh
# Generated by Superior (v${WRAPPER_VERSION}) to capture Claude usage for its
# terminal topbar. Safe to delete — Superior recreates it. It stores the status
# JSON, then runs your previous status line unchanged.
STATUS_DIR=${shellSingleQuote(dir)}
PREV=${shellSingleQuote(prevCommand)}
payload=$(cat)
sid=$(printf '%s' "$payload" | sed -n 's/.*"session_id"[[:space:]]*:[[:space:]]*"\\([0-9A-Za-z-]*\\)".*/\\1/p' | head -n1)
if [ -n "$sid" ]; then
  mkdir -p "$STATUS_DIR" 2>/dev/null
  printf '%s' "$payload" > "$STATUS_DIR/$sid.json.tmp" 2>/dev/null && mv "$STATUS_DIR/$sid.json.tmp" "$STATUS_DIR/$sid.json" 2>/dev/null
fi
if [ -n "$PREV" ]; then
  printf '%s' "$payload" | eval "$PREV"
fi
`
}

interface ClaudeSettings {
  statusLine?: { type?: string; command?: string; padding?: number }
  [key: string]: unknown
}

function readSettings(file: string): ClaudeSettings | null {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf-8')) as ClaudeSettings
  } catch (err) {
    // Missing file is fine (we create one); a malformed file is not — never
    // clobber settings we can't parse.
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return {}
    return null
  }
}

/**
 * Ensure the config dir backing `command` routes its status line through the
 * Superior wrapper. Idempotent. A no-op for non-Claude commands and on Windows.
 * Returns true when the wrapper is in place.
 */
export function ensureClaudeStatusline(command: string): boolean {
  if (isWindows) return false
  const configDir = resolveClaudeConfigDir(command)
  if (!configDir) return false

  const wrapper = wrapperPath(configDir)
  const settingsFile = path.join(configDir, 'settings.json')

  try {
    fs.mkdirSync(statusDir(), { recursive: true })

    const settings = readSettings(settingsFile)
    if (!settings) return false // unparseable — leave it untouched

    const current = settings.statusLine?.command
    const alreadyOurs = current === wrapper

    // Generate the wrapper on first install, when it's gone missing, or when the
    // template version bumps. When taking over, capture the user's existing command
    // so we can chain it; when already ours, keep the command the existing wrapper
    // baked in (the live command is the wrapper itself, so re-reading it is wrong).
    const stale = alreadyOurs && !wrapperIsCurrent(wrapper)
    if (!alreadyOurs || stale) {
      const prev = alreadyOurs ? readBakedPrev(wrapper) : current ?? ''
      fs.writeFileSync(wrapper, wrapperScript(prev), { mode: 0o755 })
    }

    if (!alreadyOurs) {
      // Capture the genuine original (settings.statusLine is still theirs here)
      // before we overwrite it, so disabling tracking can put it back verbatim.
      writeBackup(configDir, settings.statusLine)
      settings.statusLine = {
        type: 'command',
        command: wrapper,
        ...(settings.statusLine?.padding !== undefined
          ? { padding: settings.statusLine.padding }
          : {})
      }
      // Atomic replace so a Claude reading settings.json never sees a half-written file.
      const tmp = `${settingsFile}.superior.tmp`
      fs.writeFileSync(tmp, `${JSON.stringify(settings, null, 2)}\n`, 'utf-8')
      fs.renameSync(tmp, settingsFile)
    }
    return true
  } catch {
    return false // best-effort — usage simply falls back to transcript data
  }
}

/** True when an existing wrapper was generated by the current template version. */
function wrapperIsCurrent(wrapper: string): boolean {
  try {
    return fs.readFileSync(wrapper, 'utf-8').includes(`(v${WRAPPER_VERSION})`)
  } catch {
    return false // missing/unreadable — treat as stale so it gets regenerated
  }
}

/** Recover the previous command baked into an existing wrapper (PREV='...'). */
function readBakedPrev(wrapper: string): string {
  try {
    const text = fs.readFileSync(wrapper, 'utf-8')
    const m = text.match(/^PREV='((?:[^'\\]|\\.|'\\'')*)'/m)
    if (!m) return ''
    return m[1].replace(/'\\''/g, `'`)
  } catch {
    return ''
  }
}

/**
 * Undo {@link ensureClaudeStatusline} for one config dir: if its settings still
 * point at our wrapper, put the original statusLine back (from the persisted
 * backup, falling back to the command baked into the wrapper), then remove our
 * wrapper + backup. Idempotent; a no-op when the dir was never taken over.
 */
function restoreStatusline(configDir: string): void {
  const wrapper = wrapperPath(configDir)
  const backup = backupPath(configDir)
  const settingsFile = path.join(configDir, 'settings.json')

  try {
    const settings = readSettings(settingsFile)
    // Only rewrite settings we can parse and that still reference our wrapper —
    // never clobber a status line the user has since set to something else.
    if (settings && settings.statusLine?.command === wrapper) {
      const saved = readBackup(backup)
      let restored: ClaudeSettings['statusLine'] | null
      if (saved) {
        restored = saved.statusLine
      } else {
        const prev = readBakedPrev(wrapper)
        restored = prev ? { type: 'command', command: prev } : null
      }
      if (restored) settings.statusLine = restored
      else delete settings.statusLine
      const tmp = `${settingsFile}.superior.tmp`
      fs.writeFileSync(tmp, `${JSON.stringify(settings, null, 2)}\n`, 'utf-8')
      fs.renameSync(tmp, settingsFile)
    }
  } catch {
    // Leave settings as-is; we still clear our artifacts below.
  }

  // Best-effort cleanup of our own files now that nothing references them.
  try {
    fs.rmSync(wrapper, { force: true })
    fs.rmSync(backup, { force: true })
  } catch {
    /* ignore */
  }
}

/** Public: undo the wrapper for the config dir backing `command`. */
export function removeClaudeStatusline(command: string): void {
  if (isWindows) return
  const configDir = resolveClaudeConfigDir(command)
  if (configDir) restoreStatusline(configDir)
}

/**
 * Restore every config dir we ever took over, discovered from the backup files
 * in the status dir. Used when usage tracking is switched off so the takeover is
 * fully reversible regardless of which sessions are currently running.
 */
export function restoreAllClaudeStatuslines(): void {
  if (isWindows) return
  let names: string[]
  try {
    names = fs.readdirSync(statusDir())
  } catch {
    return // no status dir → nothing was ever installed
  }
  for (const name of names) {
    if (!name.startsWith('statusline-backup-') || !name.endsWith('.json')) continue
    const saved = readBackup(path.join(statusDir(), name))
    if (saved) restoreStatusline(saved.configDir)
  }
}
